### ISSUE TITLE
WIP

### ISSUE THREAD

**Issue by pacomms** [ScreepsMods/screepsmod-web-client#1]
Hi M8, just wondered if you are still working on this ? i tried tp install as mod but when i access i get Cannot GET /client , is there an easy fix, would love this so i can check my screeps on server when out n about on phone :-) 

Thanks

**Comment by pacomms** [comment]
Ok so got it working now however no graphics are loaded but it is connected ?

**Comment by AlinaNova21** [comment]
I do still work on it on occasion, otherwise its not actively developed. It does not always work correctly in its current state.
